name: "Workflow Dispatch"
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  call-lint:
    name: "Lint"
    uses: ./.github/workflows/lint.yml

  call-build:
    name: "Build & Test"
    uses: ./.github/workflows/build.yml

  call-staging:
    name: "Deploy staging"
    if: ${{ github.ref_name != 'main' }}
    needs: [call-lint, call-build]
    uses: ./.github/workflows/staging.yml
    secrets: inherit

  call-release:
    name: "Release"
    if: ${{ github.ref_protected == true }}
    needs: [call-lint, call-build]
    uses: ./.github/workflows/release.yml
    secrets: inherit
