name: "Release"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  
  release-npm:
    name: "Semantic Release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "npm"

      - name: "Obtain Github App token"
        id: app-token
        uses: getsentry/action-github-app-token@v3
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: "Clean install dependencies"
        run: npm ci

      - name: "Build"
        run: npm run build

      - name: "Execute Semantic Release"
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  production-deploy:
    name: "Deploy Production"
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://data-api.cheqd.io/

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          preCommands: npm ci
          command: deploy
          secrets: |
            WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
