name: "Deploy Staging"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  
  staging-deploy:
    name: "Cloudflare - Staging"
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://data-api-staging.cheqd.io/

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          preCommands: npm ci
          command: deploy --env staging
          secrets: |
            WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
